# Generated by Django 4.2 on 2024-12-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiostation',
            name='image',
            field=models.ImageField(upload_to='radio_images/'),
        ),
    ]
