# Generated by Django 4.2 on 2024-12-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_alter_radiostation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiostation',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='radiostation',
            name='call_sign',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='radiostation',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='radiostation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='radiostation',
            name='slogan',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='radiostation',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
